{
    "name": "Smart Customer Rating AI",
    "version": "19.0.1.1.1",
    "summary": "AI-powered customer rating with badges, scoring, and smart insights",
    "author": "LogicLayer",
    "website": "https://logiclayerhq.com",
    "category": "Sales/CRM",
    "license": "OPL-1",
    "price": 9.99,
    "currency": "USD",
    "depends": ["base", "contacts", "crm", "sales", "account"],
    "data": [
        "security/ir.model.access.csv",
        "data/rating_rule_data.xml",
        "data/ir_cron_data.xml",
        "data/demo_data.xml",
        "views/rating_views.xml",
        "views/res_partner_views.xml",
        "views/rating_rule_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/ll_rating_recompute_wizard_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "images": [
        "static/description/thumbnail.png",
    ],
    "application": True,
    "installable": True,
}
